packages:
  - packages/*

onlyBuiltDependencies:
  - "@swc/core"
  - canvas
  - esbuild
  - webgpu

catalog:
  vite: ^7.2.7
  unplugin-dts: 1.0.0-beta.6
  "@biomejs/biome": ^2.4.4

minimumReleaseAge: 10080 # 7days
